# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/aoo/OME

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/aoo/OME

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/aoo/OME/CMakeFiles /home/aoo/OME//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/aoo/OME/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ome_parser

# Build rule for target.
ome_parser: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ome_parser
.PHONY : ome_parser

# fast build rule for target.
ome_parser/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ome_parser.dir/build.make CMakeFiles/ome_parser.dir/build
.PHONY : ome_parser/fast

#=============================================================================
# Target rules for targets named ome

# Build rule for target.
ome: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ome
.PHONY : ome

# fast build rule for target.
ome/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ome.dir/build.make CMakeFiles/ome.dir/build
.PHONY : ome/fast

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ome.dir/build.make CMakeFiles/ome.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ome.dir/build.make CMakeFiles/ome.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ome.dir/build.make CMakeFiles/ome.dir/main.cpp.s
.PHONY : main.cpp.s

src/Acceptor.o: src/Acceptor.cpp.o
.PHONY : src/Acceptor.o

# target to build an object file
src/Acceptor.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ome_parser.dir/build.make CMakeFiles/ome_parser.dir/src/Acceptor.cpp.o
.PHONY : src/Acceptor.cpp.o

src/Acceptor.i: src/Acceptor.cpp.i
.PHONY : src/Acceptor.i

# target to preprocess a source file
src/Acceptor.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ome_parser.dir/build.make CMakeFiles/ome_parser.dir/src/Acceptor.cpp.i
.PHONY : src/Acceptor.cpp.i

src/Acceptor.s: src/Acceptor.cpp.s
.PHONY : src/Acceptor.s

# target to generate assembly for a file
src/Acceptor.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ome_parser.dir/build.make CMakeFiles/ome_parser.dir/src/Acceptor.cpp.s
.PHONY : src/Acceptor.cpp.s

src/Client.o: src/Client.cpp.o
.PHONY : src/Client.o

# target to build an object file
src/Client.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ome_parser.dir/build.make CMakeFiles/ome_parser.dir/src/Client.cpp.o
.PHONY : src/Client.cpp.o

src/Client.i: src/Client.cpp.i
.PHONY : src/Client.i

# target to preprocess a source file
src/Client.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ome_parser.dir/build.make CMakeFiles/ome_parser.dir/src/Client.cpp.i
.PHONY : src/Client.cpp.i

src/Client.s: src/Client.cpp.s
.PHONY : src/Client.s

# target to generate assembly for a file
src/Client.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ome_parser.dir/build.make CMakeFiles/ome_parser.dir/src/Client.cpp.s
.PHONY : src/Client.cpp.s

src/ClientManager.o: src/ClientManager.cpp.o
.PHONY : src/ClientManager.o

# target to build an object file
src/ClientManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ome_parser.dir/build.make CMakeFiles/ome_parser.dir/src/ClientManager.cpp.o
.PHONY : src/ClientManager.cpp.o

src/ClientManager.i: src/ClientManager.cpp.i
.PHONY : src/ClientManager.i

# target to preprocess a source file
src/ClientManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ome_parser.dir/build.make CMakeFiles/ome_parser.dir/src/ClientManager.cpp.i
.PHONY : src/ClientManager.cpp.i

src/ClientManager.s: src/ClientManager.cpp.s
.PHONY : src/ClientManager.s

# target to generate assembly for a file
src/ClientManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ome_parser.dir/build.make CMakeFiles/ome_parser.dir/src/ClientManager.cpp.s
.PHONY : src/ClientManager.cpp.s

src/Epoll.o: src/Epoll.cpp.o
.PHONY : src/Epoll.o

# target to build an object file
src/Epoll.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ome_parser.dir/build.make CMakeFiles/ome_parser.dir/src/Epoll.cpp.o
.PHONY : src/Epoll.cpp.o

src/Epoll.i: src/Epoll.cpp.i
.PHONY : src/Epoll.i

# target to preprocess a source file
src/Epoll.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ome_parser.dir/build.make CMakeFiles/ome_parser.dir/src/Epoll.cpp.i
.PHONY : src/Epoll.cpp.i

src/Epoll.s: src/Epoll.cpp.s
.PHONY : src/Epoll.s

# target to generate assembly for a file
src/Epoll.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ome_parser.dir/build.make CMakeFiles/ome_parser.dir/src/Epoll.cpp.s
.PHONY : src/Epoll.cpp.s

src/Ome.o: src/Ome.cpp.o
.PHONY : src/Ome.o

# target to build an object file
src/Ome.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ome_parser.dir/build.make CMakeFiles/ome_parser.dir/src/Ome.cpp.o
.PHONY : src/Ome.cpp.o

src/Ome.i: src/Ome.cpp.i
.PHONY : src/Ome.i

# target to preprocess a source file
src/Ome.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ome_parser.dir/build.make CMakeFiles/ome_parser.dir/src/Ome.cpp.i
.PHONY : src/Ome.cpp.i

src/Ome.s: src/Ome.cpp.s
.PHONY : src/Ome.s

# target to generate assembly for a file
src/Ome.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ome_parser.dir/build.make CMakeFiles/ome_parser.dir/src/Ome.cpp.s
.PHONY : src/Ome.cpp.s

src/Reactor.o: src/Reactor.cpp.o
.PHONY : src/Reactor.o

# target to build an object file
src/Reactor.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ome_parser.dir/build.make CMakeFiles/ome_parser.dir/src/Reactor.cpp.o
.PHONY : src/Reactor.cpp.o

src/Reactor.i: src/Reactor.cpp.i
.PHONY : src/Reactor.i

# target to preprocess a source file
src/Reactor.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ome_parser.dir/build.make CMakeFiles/ome_parser.dir/src/Reactor.cpp.i
.PHONY : src/Reactor.cpp.i

src/Reactor.s: src/Reactor.cpp.s
.PHONY : src/Reactor.s

# target to generate assembly for a file
src/Reactor.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ome_parser.dir/build.make CMakeFiles/ome_parser.dir/src/Reactor.cpp.s
.PHONY : src/Reactor.cpp.s

src/Server.o: src/Server.cpp.o
.PHONY : src/Server.o

# target to build an object file
src/Server.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ome_parser.dir/build.make CMakeFiles/ome_parser.dir/src/Server.cpp.o
.PHONY : src/Server.cpp.o

src/Server.i: src/Server.cpp.i
.PHONY : src/Server.i

# target to preprocess a source file
src/Server.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ome_parser.dir/build.make CMakeFiles/ome_parser.dir/src/Server.cpp.i
.PHONY : src/Server.cpp.i

src/Server.s: src/Server.cpp.s
.PHONY : src/Server.s

# target to generate assembly for a file
src/Server.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ome_parser.dir/build.make CMakeFiles/ome_parser.dir/src/Server.cpp.s
.PHONY : src/Server.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... ome"
	@echo "... ome_parser"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... src/Acceptor.o"
	@echo "... src/Acceptor.i"
	@echo "... src/Acceptor.s"
	@echo "... src/Client.o"
	@echo "... src/Client.i"
	@echo "... src/Client.s"
	@echo "... src/ClientManager.o"
	@echo "... src/ClientManager.i"
	@echo "... src/ClientManager.s"
	@echo "... src/Epoll.o"
	@echo "... src/Epoll.i"
	@echo "... src/Epoll.s"
	@echo "... src/Ome.o"
	@echo "... src/Ome.i"
	@echo "... src/Ome.s"
	@echo "... src/Reactor.o"
	@echo "... src/Reactor.i"
	@echo "... src/Reactor.s"
	@echo "... src/Server.o"
	@echo "... src/Server.i"
	@echo "... src/Server.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

